- hosts: swarm_master
  tasks:
    - name: Run the Service
      docker_swarm_service:
        image: fx8350:5000/zFlux:latest
        name: zFlux
        state: present
        resolve_image: yes
        replicas: 1
